Implement missing idris_mkFileError for windows rts files
 - work around error: undefined reference to `idris_mkFileError'
 - minor code formatting corrections (use 4 spaces, no tailoring spaces)